{
 "title": "Storage - AWS Deep Glacier",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bytes Stored in AWS Deep Glacier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(total_bytes_to_aws) FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "Files Archived to AWS Deep Glacier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(bundle_files_contained) FROM aws_backup.bundle_information LIMIT 50 "
    }
   ]
  },
  {
   "title": "Objects in AWS Deep Glacier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT COUNT(bundle_file_name)*2 FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "Average Object Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(total_bytes_to_aws)/(COUNT(bundle_file_name)*2) as \"Overall\" FROM aws_backup.bundle_information"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(bundle_encrypted_size_bytes)/(COUNT(bundle_file_name)) as \"Bundles Only\" FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "File Bundles in AWS Deep Glacier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT COUNT(bundle_file_name) FROM aws_backup.bundle_information LIMIT 50 "
    }
   ]
  },
  {
   "title": "Largest Bundle in AWS Deep Glacier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT max(bundle_encrypted_size_bytes) FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "Monthly Cost for Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(total_bytes_to_aws)/1024/1024/1024*0.00099 FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "Annual Cost for Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(total_bytes_to_aws)/1024/1024/1024*0.00099*12 FROM aws_backup.bundle_information"
    }
   ]
  },
  {
   "title": "Capacity Used by Data Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "select sum(bundle_encrypted_size_bytes) as \"Data Bundles\", sum(bundle_manifest_encrypted_size_bytes) as \"Manifests\" from bundle_information"
    }
   ]
  },
  {
   "title": "Capacity Saved by Compression",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT (SUM(bundle_file_size_bytes)+SUM(bundle_manifest_size_bytes))-(SUM(bundle_encrypted_size_bytes)+SUM(bundle_manifest_encrypted_size_bytes)) FROM aws_backup.bundle_information "
    }
   ]
  },
  {
   "title": "Money Saved Monthly with Compression",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT ((SUM(bundle_file_size_bytes)+SUM(bundle_manifest_size_bytes))-(SUM(bundle_encrypted_size_bytes)+SUM(bundle_manifest_encrypted_size_bytes)))/1024/1024/1024*0.00099 FROM aws_backup.bundle_information "
    }
   ]
  },
  {
   "title": "Data Block Compression Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "suffix:x" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT (SUM(bundle_file_size_bytes)+SUM(bundle_manifest_size_bytes))/(SUM(bundle_encrypted_size_bytes)+SUM(bundle_manifest_encrypted_size_bytes)) FROM aws_backup.bundle_information "
    }
   ]
  },
  {
   "title": "Bundle Size Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"0-100MB\" from bundle_information where bundle_encrypted_size_bytes > 0 and bundle_encrypted_size_bytes < 100000000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"100MB-1GB\" from bundle_information where bundle_encrypted_size_bytes > 100000000 and bundle_encrypted_size_bytes < 1000000000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"1GB-10GB\" from bundle_information where bundle_encrypted_size_bytes > 1000000000 and bundle_encrypted_size_bytes < 10000000000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"10GB-100GB\" from bundle_information where bundle_encrypted_size_bytes > 10000000000 and bundle_encrypted_size_bytes < 100000000000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"100GB+\" from bundle_information where bundle_encrypted_size_bytes > 100000000000"
    }
   ]
  },
  {
   "title": "Files Contained in Bundle Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"0-100\" from bundle_information where bundle_files_contained > 0 and bundle_files_contained < 100"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"100-500\" from bundle_information where bundle_files_contained > 100 and bundle_files_contained < 500"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"500-1000\" from bundle_information where bundle_files_contained > 500 and bundle_files_contained < 1000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"1000-5000\" from bundle_information where bundle_encrypted_size_bytes > 1000 and bundle_encrypted_size_bytes < 5000"
    },
    {
     "dataset": "aws_backup",
     "rawSql": "select count(bundle_number) as \"5000+\" from bundle_information where bundle_files_contained > 5000"
    }
   ]
  },
  {
   "title": "File/Object Count Reduction Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "suffix:x" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "aws_backup",
     "rawSql": "SELECT SUM(bundle_files_contained)/(COUNT(bundle_file_name)*2) FROM aws_backup.bundle_information "
    }
   ]
  }
 ]
}